var ETERNA_PAINTINGS = [
  {
    "number": 1,
    "code": "AEE101",
    "title": "SOLI E COMUNICARE",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "50 x 50 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 370,
    "note": "Unique piece",
    "description": "Solitude and the need to communicate. The figures seem to move along different paths, yet they share the same space, like people seeking contact without truly managing to meet.",
    "image": "images/paintings/1.jpeg",
    "extraImages": [
      "images/paintings/details/1-1.jfif"
    ]
  },
  {
    "number": 2,
    "code": "AEE102",
    "title": "LINGUAGGIO ETERNO",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "90 x 30 cm",
    "available": false,
    "status": "Sold",
    "statusClass": "sold",
    "price": 0,
    "note": "Unique piece",
    "description": "Each mark is a voice, each color is the possibility of communication. Art becomes a language that crosses eras, cultures, and silences.",
    "image": "images/paintings/2.jpeg",
    "extraImages": []
  },
  {
    "number": 3,
    "code": "AEE103",
    "title": "SGUARDO NEL CUORE",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "50 x 50 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 380,
    "note": "Unique piece",
    "description": "Four fading sorrows accompany a gaze immersed in the heart.",
    "image": "images/paintings/3.jpeg",
    "extraImages": []
  },
  {
    "number": 4,
    "code": "AEE104",
    "title": "SGARDI IN CITTA",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "90 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 400,
    "note": "Unique piece",
    "description": "A multitude of colored eyes, a city, and gazes observing one another.",
    "image": "images/paintings/4.jpeg",
    "extraImages": []
  },
  {
    "number": 5,
    "code": "AEE105",
    "title": "SGUARDI TROPICALI",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 60 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 380,
    "note": "Unique piece",
    "description": "Golden gazes appear among profiles that multiply inside tropical vegetation.",
    "image": "images/paintings/5.jpeg",
    "extraImages": []
  },
  {
    "number": 6,
    "code": "AEE106",
    "title": "SGUARDI UNIVERSALI",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "60 x 60 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 380,
    "note": "Unique piece",
    "description": "Fixed points, blue and red gazes, and a vortex-like expansion of the universe.",
    "image": "images/paintings/6.jpeg",
    "extraImages": []
  },
  {
    "number": 7,
    "code": "AEE107",
    "title": "SGUARDO SBARRATO",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": false,
    "status": "Sold",
    "statusClass": "sold",
    "price": 0,
    "note": "Unique piece",
    "description": "Original abstract artwork by Marcello Castagna, presented by Eterna Espressione.",
    "image": "images/paintings/7.jpeg",
    "extraImages": []
  },
  {
    "number": 8,
    "code": "AEE108",
    "title": "OCCHI NELLA FORESTA",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "50 x 50 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 370,
    "note": "Unique piece",
    "description": "In the depth of the vegetation, two large eyes are carved by tribal marks.",
    "image": "images/paintings/8.jpeg",
    "extraImages": []
  },
  {
    "number": 9,
    "code": "AEE109",
    "title": "OCCHIO DEL CUORE",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 390,
    "note": "Unique piece",
    "description": "Freedom, identity, love, and inclusion. Every difference becomes color.",
    "image": "images/paintings/9.jpeg",
    "extraImages": []
  },
  {
    "number": 10,
    "code": "AEE110",
    "title": "IL BULLO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 370,
    "note": "Unique piece",
    "description": "The bully and fear. Some fears belong to childhood, yet they keep knocking at the door of the adult self.",
    "image": "images/paintings/10.jpeg",
    "extraImages": []
  },
  {
    "number": 11,
    "code": "AEE111",
    "title": "VORTICE INTERIORE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 60 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 390,
    "note": "Unique piece",
    "description": "A deep expressive search, where the central spiral acts as a visual vortex.",
    "image": "images/paintings/11.jpeg",
    "extraImages": []
  },
  {
    "number": 12,
    "code": "AEE112",
    "title": "OCCHI IN GIARDINO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "50 x 50 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 340,
    "note": "Unique piece",
    "description": "Nature merges with the mystical, and the vision looks into the soul.",
    "image": "images/paintings/12.jpeg",
    "extraImages": []
  },
  {
    "number": 13,
    "code": "AEE113",
    "title": "CUORE COSMICO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "50 x 50 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 340,
    "note": "Unique piece",
    "description": "A visionary work. A central eye, a ruby-red gaze inside the black hole.",
    "image": "images/paintings/13.jpeg",
    "extraImages": []
  },
  {
    "number": 14,
    "code": "AEE114",
    "title": "ILGRIDO SILENZIOSO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 60 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 400,
    "note": "Unique piece",
    "description": "A gaze that explodes into silence. A scream that needs no voice.",
    "image": "images/paintings/14.jpeg",
    "extraImages": []
  },
  {
    "number": 15,
    "code": "AEE115",
    "title": "UN RICHIAMO ALLA LUNA",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 370,
    "note": "Unique piece",
    "description": "We feel it and we see it: the rhythm of the lunar cycle.",
    "image": "images/paintings/15.jpeg",
    "extraImages": []
  },
  {
    "number": 16,
    "code": "AEE116",
    "title": "TRE SGUARDI",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "50 x 50 cm",
    "available": false,
    "status": "Sold",
    "statusClass": "sold",
    "price": 0,
    "note": "Unique original artwork",
    "description": "Original abstract artwork by Marcello Castagna, presented by Eterna Espressione.",
    "image": "images/paintings/16.jpeg",
    "extraImages": []
  },
  {
    "number": 17,
    "code": "AEE117",
    "title": "SOUL IN LOVE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "50 x 50 cm",
    "available": false,
    "status": "Sold",
    "statusClass": "sold",
    "price": 0,
    "note": "Unique original artwork",
    "description": "Original abstract artwork by Marcello Castagna, presented by Eterna Espressione.",
    "image": "images/paintings/17.jpeg",
    "extraImages": []
  },
  {
    "number": 18,
    "code": "AEE118",
    "title": "VOLTO IMPOSSIBILE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "50 x 50 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 250,
    "note": "Unique piece",
    "description": "Intense and penetrating eyes observe beyond appearances, searching for what we often hide.",
    "image": "images/paintings/18.jpeg",
    "extraImages": []
  },
  {
    "number": 19,
    "code": "AEE119",
    "title": "DOPPIA VISIONE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 490,
    "note": "Unique piece",
    "description": "Double vision. Movement and vibration. Perceptions held within the same space.",
    "image": "images/paintings/19.jpeg",
    "extraImages": []
  },
  {
    "number": 20,
    "code": "AEE120",
    "title": "ASSE DELLO SGUARDO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "90 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 440,
    "note": "Unique piece",
    "description": "A gaze aligns along a thread of light.",
    "image": "images/paintings/20.jpeg",
    "extraImages": []
  },
  {
    "number": 21,
    "code": "AEE121",
    "title": "PUNTO ROJO",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": false,
    "status": "Sold",
    "statusClass": "sold",
    "price": 0,
    "note": "Unique piece",
    "description": "Original abstract artwork by Marcello Castagna, presented by Eterna Espressione.",
    "image": "images/paintings/21.jpeg",
    "extraImages": []
  },
  {
    "number": 22,
    "code": "AEE122",
    "title": "DANZA DI PRIMAVERA",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 370,
    "note": "Unique piece",
    "description": "Stylized flowers whirl through spring.",
    "image": "images/paintings/22.jpeg",
    "extraImages": []
  },
  {
    "number": 23,
    "code": "AEE123",
    "title": "FRAMMENTI DI MEMORIA",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "To be confirmed",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 390,
    "note": "Unique piece",
    "description": "Intense and layered: the memory of the gaze.",
    "image": "images/paintings/23.jpeg",
    "extraImages": []
  },
  {
    "number": 24,
    "code": "AEE124",
    "title": "LA STIRPE CHE OSSERVA",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 390,
    "note": "Unique piece",
    "description": "Lineage. Gazes passed down from eye to eye.",
    "image": "images/paintings/24.jpeg",
    "extraImages": []
  },
  {
    "number": 25,
    "code": "AEE125",
    "title": "SETTE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 370,
    "note": "Unique piece",
    "description": "Seven. Gazes with wounds.",
    "image": "images/paintings/25.jpeg",
    "extraImages": []
  },
  {
    "number": 26,
    "code": "AEE126",
    "title": "SGUARDO CHE RACCOGLIE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 60 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 400,
    "note": "Unique piece",
    "description": "A point that attracts and holds the energy of the gaze.",
    "image": "images/paintings/26.jpeg",
    "extraImages": []
  },
  {
    "number": 27,
    "code": "AEE127",
    "title": "RADICE VERTICALE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "90 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 410,
    "note": "Unique piece",
    "description": "A vibrant root toward a gaze. A vertical tension.",
    "image": "images/paintings/27.jpeg",
    "extraImages": []
  },
  {
    "number": 28,
    "code": "AEE128",
    "title": "MOLTITUDINE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 430,
    "note": "Unique piece",
    "description": "Vision everywhere. Diffuse vision. Gazes without hierarchy. One body, many unsettled gazes.",
    "image": "images/paintings/28.jpeg",
    "extraImages": []
  },
  {
    "number": 29,
    "code": "AEE129",
    "title": "COME TUTTO È COMINCIATO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": false,
    "status": "Auction",
    "statusClass": "auction",
    "price": 560,
    "note": "Unique piece",
    "description": "Origin with a witness.",
    "image": "images/paintings/29.jpeg",
    "extraImages": []
  },
  {
    "number": 30,
    "code": "AEE130",
    "title": "L'OCCHIO NEL PROFILO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 330,
    "note": "Unique piece",
    "description": "A profile gaze. Does it define who we are?",
    "image": "images/paintings/30.jpeg",
    "extraImages": []
  },
  {
    "number": 31,
    "code": "AEE131",
    "title": "SGUARDO TORMENTATO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 310,
    "note": "Unique piece",
    "description": "A gaze with the idea of a heartbeat. Tormented. An instant.",
    "image": "images/paintings/31.jpeg",
    "extraImages": []
  },
  {
    "number": 32,
    "code": "AEE132",
    "title": "SGUARDO RIFLESSO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 310,
    "note": "Unique piece",
    "description": "Identical and mirrored. A silent dialogue.",
    "image": "images/paintings/32.jpeg",
    "extraImages": []
  },
  {
    "number": 33,
    "code": "AEE133",
    "title": "TRIPLO SGUARDO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 310,
    "note": "Unique piece",
    "description": "Three perspectives. Three dimensions of being.",
    "image": "images/paintings/33.jpeg",
    "extraImages": []
  },
  {
    "number": 34,
    "code": "AEE134",
    "title": "ABBRACCIO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "To be confirmed",
    "available": false,
    "status": "Sold",
    "statusClass": "sold",
    "price": 0,
    "note": "Unique piece",
    "description": "Original abstract artwork by Marcello Castagna, presented by Eterna Espressione.",
    "image": "images/paintings/34.jpeg",
    "extraImages": []
  },
  {
    "number": 35,
    "code": "AEE135",
    "title": "CAOTICO,ISTINTIVO,VIBRANTE",
    "artist": "Marcello Castagna",
    "year": "2023",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 520,
    "note": "Unique piece",
    "description": "A timeless language.",
    "image": "images/paintings/35.jpeg",
    "extraImages": []
  },
  {
    "number": 36,
    "code": "AEE136",
    "title": "RADICE ORENTALE",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 300,
    "note": "Unique piece",
    "description": "Growth and expansion.",
    "image": "images/paintings/36.jpeg",
    "extraImages": []
  },
  {
    "number": 37,
    "code": "AEE137",
    "title": "OTTO DORATI",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "90 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 450,
    "note": "Unique piece",
    "description": "Hypnotic.",
    "image": "images/paintings/37.jpeg",
    "extraImages": []
  },
  {
    "number": 38,
    "code": "AEE138",
    "title": "RISVEGLIO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "90 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 430,
    "note": "Unique piece",
    "description": "Emergence. Coming into the light and crossing the threshold.",
    "image": "images/paintings/38.jpeg",
    "extraImages": []
  },
  {
    "number": 39,
    "code": "AEE139",
    "title": "OCCHI IN FILO SPINATO",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 330,
    "note": "Unique piece",
    "description": "Trapped gazes.",
    "image": "images/paintings/39.jpeg",
    "extraImages": []
  },
  {
    "number": 40,
    "code": "AEE140",
    "title": "CAMPO VISIVO",
    "artist": "Marcello Castagna",
    "year": "2026",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 520,
    "note": "Unique piece",
    "description": "A fragmented field of vision.",
    "image": "images/paintings/40.jpeg",
    "extraImages": []
  },
  {
    "number": 41,
    "code": "AEE141",
    "title": "PANOPTICON",
    "artist": "Marcello Castagna",
    "year": "2024",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 510,
    "note": "Unique piece",
    "description": "Control and surveillance.",
    "image": "images/paintings/41.jpeg",
    "extraImages": []
  },
  {
    "number": 42,
    "code": "AEE142",
    "title": "MAPPE INTERIORI",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 480,
    "note": "Unique piece",
    "description": "The most important journey is the one toward oneself.",
    "image": "images/paintings/42.jpeg",
    "extraImages": []
  },
  {
    "number": 43,
    "code": "AEE143",
    "title": "OCCHI SPETTINATI",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 520,
    "note": "Unique piece",
    "description": "Eyes tousled by life. Occhi Spettinati is an invitation to see beyond the surface.",
    "image": "images/paintings/43.jpeg",
    "extraImages": []
  },
  {
    "number": 44,
    "code": "AEE144",
    "title": "VOLTI LACERATI",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic diptych",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 450,
    "note": "Unique piece",
    "description": "Cubist faces with open wounds. The violence behind a gaze.",
    "image": "images/paintings/44.jpeg",
    "extraImages": []
  },
  {
    "number": 45,
    "code": "AEE145",
    "title": "FINESTRA SULL'ANIMA",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic",
    "dimensions": "60 x 30 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 430,
    "note": "Unique piece",
    "description": "The window onto the soul, what remains. Three points like final heartbeats. The ladder, traces of a suspended time.",
    "image": "images/paintings/45.jpeg",
    "extraImages": []
  },
  {
    "number": 46,
    "code": "AEE146",
    "title": "OCCHI NELLA TRAMA",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic",
    "dimensions": "60 x 60 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 390,
    "note": "Unique piece",
    "description": "To see is already to become part of what is observed.",
    "image": "images/paintings/46.jpeg",
    "extraImages": []
  },
  {
    "number": 47,
    "code": "AEE147",
    "title": "SGUARDO CONTROTEMPO",
    "artist": "Marcello Castagna",
    "year": "2026",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 520,
    "note": "Unique piece",
    "description": "Outside time and against the current of contemporary society.",
    "image": "images/paintings/47.jpeg",
    "extraImages": []
  },
  {
    "number": 48,
    "code": "AEE148",
    "title": "ANIMA FRANTUMATA",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 490,
    "note": "Unique piece",
    "description": "The shattered soul sees and resists through every single gaze.",
    "image": "images/paintings/48.jpeg",
    "extraImages": []
  },
  {
    "number": 49,
    "code": "AEE149",
    "title": "LA SOGLIA DELL'IO",
    "artist": "Marcello Castagna",
    "year": "2026",
    "technique": "Acrylic",
    "dimensions": "60 x 60 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 440,
    "note": "Unique piece",
    "description": "Every transformation begins before a threshold. The threshold of the self.",
    "image": "images/paintings/49.jpeg",
    "extraImages": []
  },
  {
    "number": 50,
    "code": "AEE150",
    "title": "IL CIRCOLO DI WILLIS",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 550,
    "note": "Unique piece",
    "description": "An arterial network that nourishes the brain. An emotional landscape. Every branch a thought, every neuron a memory, every eye a consciousness.",
    "image": "images/paintings/50.jpeg",
    "extraImages": []
  },
  {
    "number": 51,
    "code": "AEE151",
    "title": "OCCHI DEL TRAMONTO",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic",
    "dimensions": "60 x 60 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 460,
    "note": "Unique piece",
    "description": "There are sunsets that do not merely let themselves be watched. They choose to look inside us.",
    "image": "images/paintings/51.jpeg",
    "extraImages": []
  },
  {
    "number": 52,
    "code": "AEE152",
    "title": "DUALITY",
    "artist": "Marcello Castagna",
    "year": "2025",
    "technique": "Acrylic",
    "dimensions": "100 x 70 cm",
    "available": true,
    "status": "Available",
    "statusClass": "available",
    "price": 540,
    "note": "Unique piece",
    "description": "Red, the meeting point. Contradictory, different, yet inevitably part of the same reality.",
    "image": "images/paintings/52.jpeg",
    "extraImages": []
  }
];
